### ISSUE TITLE
Travis isn't happy.

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#10]
It seems like adding my PATH and resolving the merge conflicts this caused has broken the code. I don't know how though. Also, it doesn't seem to work om my computer again, and I can't find the 'load functions' file, because I get a 'could not find function' error.

Please help. I don't have a clue. 0.o

**Comment by richelbilderbeek** [comment]
You should seperate the paths by a comma:

```
c(
  "a"
  "b"
)
```

should be

```
c(
  "a", # note the comma
  "b"
)
```

Happens to the best of us :-)

**Comment by richelbilderbeek** [comment]
Suggest: fix it, check it in, close this issue :-)

**Comment by richelbilderbeek** [comment]
Whoohoo, will Travis be happy now...?

**Comment by FemkeThon** [comment]
Seems like it!

**Comment by richelbilderbeek** [comment]
Well done! Thanks for also fixing my style error
