### ISSUE TITLE
I broke something.

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#12]
Research.demo.RMD as it is here doesn't work ( plot_posterior_nltts, line 230) and despite trying to reverse the edits I made while adding my PATH, we can't get it to work on my computer. Even while cleaning and rebuilding. It still works on Jolien's laptop, with the old version, just not on mine.

So. Can you help us find the error there?

**Comment by richelbilderbeek** [comment]
Try to install `ggplot2`, clean and rebuild, then let me know if it still fails. 

Tip: mention @richelbilderbeek to make me receive an email, or set me as the 'Assignee'

**Comment by FemkeThon** [comment]
@richelbilderbeek 

R still doesn't agree. Now it's complaining about the boundaries of a graph 'need finite xlim values' - but the line it refers to doesn't contain the function with the error. The whole vignette doesn't.

On top of that, some screen of BEAST opens at every run of the vignette.

I'm sorry, but I don't have a clue.

**Comment by richelbilderbeek** [comment]
BEAST2 produces a pop-up window upon calling the `.exe` file. Solution was to call the `.jar` file with `java -jar beast.jar`
