### ISSUE TITLE
Remove toy_example files from root folder

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#15]
The `toy_example_` files are unnecessarily in the package its root folder. This is unconventional (such files should be in `int/extdata` or `vignettes` or `testthat/tests`) and annoying. Could these be removed? I assigned the person who added these files to the repo :-)

Tip: one could add `/toy_examples_*` to `.gitignore` to allow files to be created there, but not version control them. 

Let me know if you need help.

**Comment by FemkeThon** [comment]
They are gone.
