### ISSUE TITLE
Remove Newick files from root folder

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#16]
The `Newick` files are unnecessarily in the package its root folder. This is unconventional (such files should be in int/extdata or vignettes or testthat/tests) and annoying. Could these be removed? I assigned the person who added these files to the repo :-)

Tip: one could add `/Newick*` to .gitignore to allow files to be created there, but not version control them.

Let me know if you need help.

**Comment by JolienGay** [comment]
Done! I think =P

**Comment by richelbilderbeek** [comment]
Well done! I took the liberty of closing this issue. Feel free to do so yourself next time :-)
