### ISSUE TITLE
Implement advice from book

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#19]
From the upcoming book `Efficient R programming` by Colin Gillespie and Robin Lovelace, [this URL](https://csgillespie.github.io/efficientR/general-advice.html#vectorised-code):

```
Using 1:length(x) can lead to hard-to-find bugs when x has length zero. Instead use seq_along(x) or seq_leng(length(x)). 
```

Volunteer anyone to check and fix this in our code? @FemkeThon and @JolienGay ? Assign yourself if you'd like to.

**Comment by JolienGay** [comment]
I would like to if its okay with Femke. It might be a great way to familiarize myself with the code!

**Comment by FemkeThon** [comment]
Knock yourself out, Jolien!

**Comment by JolienGay** [comment]
Is no used in this project
