### ISSUE TITLE
file.exists cannot read multiple filenames

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#26]
Error when trying to do this: filenames <- read_file(all_parameters)      (can be found in the display-dataset-parameters.Rmd):

Error in gzfile(file, "rb") : invalid 'description' argument In addition: Warning message:
In if (!file.exists(filename)) { :
  the condition has length > 1 and only the first element will be used
> show_parameter_files(filenames)

Can't find gzfile with the Ctrl-Shift-F function..

**Comment by richelbilderbeek** [comment]
The error message is correct:

```
the condition has length > 1 and only the first element will be used
```

The function `file.exists` needs to be supplied only one filename, not a vector of filenames.

I will update `read_file` to already detect the error there, unless you want to.

**Comment by richelbilderbeek** [comment]
I added a check at `read_file` via the GitHub browser, I just hope it does not break the build, as I could not verify it works.

**Comment by richelbilderbeek** [comment]
Verified that it works
