### ISSUE TITLE
Cyclic dependency error

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#27]
We've got a cyclic namespace dependency error again. I don't know where it comes from.

**Comment by richelbilderbeek** [comment]
Could you post the error message?

**Comment by FemkeThon** [comment]
Error in loadNamespace(package, c(which.lib.loc, lib.loc)) : 
  cyclic namespace dependency detected when loading 'Cer2016', already loading 'Cer2016'
Error : package or namespace load failed for 'Cer2016'
Error : unable to load R code in package 'Cer2016'
ERROR: lazy loading failed for package 'Cer2016'
* removing 'C:/Users/Stultum/Documents/R/win-library/3.2/Cer2016'
* restoring previous 'C:/Users/Stultum/Documents/R/win-library/3.2/Cer2016'

Exited with status 1.

Might share a cause with #25, but it's not the same place where I noticed it.

**Comment by richelbilderbeek** [comment]
I understood you do not have this problem anymore?

It may be caused by something (a test?) calling `library(Cer2016)`. As this test will be run by `library(Cer2016)`, one gets an infinite recursion.

Feel free to close the Issue if the problem is confirmed to be solved.

**Comment by FemkeThon** [comment]
Fixed.
