### ISSUE TITLE
NA or NULL?

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#28]
In 'demo_collect_posterior_filename.RDa' : 
line 37 :  nltt_values <- NA

Is it possible that it is safer to use NULL instead of NA?
Source: The art of R programming (Norman Matloff), Chapter 2 pages 43-44
p44:
"If we were to use NA instead of NULL in the preceding example, we would pick up an unwanted NA"
"NULL values really are counted as nonexistent, as you can see here:"

Maybe it is not necessary in our function but then I would like to know why NA is preferred over NULL here?

**Comment by richelbilderbeek** [comment]
Thanks for the reference. I read there as well: 'One use of NULL is to build up vectors in loops [...]', see [1].

I suggest to follow that advice. Feel free to replace `NA` by `NULL`.

## References

 [1] The art of R programming (Norman Matloff), Chapter 2.7.2 page 44, 'One use of NULL is to build up vectors in loops [...]'

**Comment by JolienGay** [comment]
Done, I hope I got em all!
