### ISSUE TITLE
Suggest: move verdubbelDit to other GitHub

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#34]
The function and vignette `verdubbelDit` have served their educational purpose, 
but are not a functional part of this package.

I suggest to either
1) move these to another repo
2) delete these

I suggest @JolienGay to do whatever she likes with this.

**Comment by JolienGay** [comment]
Done, also moved the 'exercise tuesday' and newick files to my useful-stuff repository.
