### ISSUE TITLE
Can't get my comparing script to work.

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#41]
@richelbilderbeek 

In Scripts -> thingy, I have a script that should compare the gamma's of the sampled tree and the posterior. I left it running for almost a day this weekend, and it still wasn't complete. I either made a mistake that doesn't show up if you just use it on the first few posteriors, or the script just takes too long - in any case, could you please take a look at it and see if there's something wrong with it?

**Comment by richelbilderbeek** [comment]
Solution: the code was finished within a minute. See the comments in the code.

```
comparison  <- NULL
counter2    <- 0
for (stat in df_posterior$gamma_stat) {
  counter  <- 0
  counter2 <- counter2 + 1
  if (!is.na(stat)){
    for (value in df_species_trees$gamma_stat){
      counter <- counter + 1
      # Check if the if statement is ever true
      testit::assert(df_posterior$filenames[counter2] != df_species_trees$filenames[counter])
      # This if statement will never be true
      if ((df_posterior$filenames[counter2] ==
           df_species_trees$filenames[counter]) && !is.na(value)){
        comparison$filenames  <- c(comparison$filenames,
                                   df_species_trees$filenames[counter])
        comparison$treenumber <- c(comparison$treenumber,
                                   df_species_trees$species_tree[counter])
        comparison$gamma_pbd  <- c(comparison$gamma_pbd, value)
        comparison$gamma_post <- c(comparison$gamma_post, stat)
        comparison$diff       <- c(comparison$diff,
                                   (value - stat))
      }
    }
  }
}
comparison <- data.frame(comparison)
```

**Comment by richelbilderbeek** [comment]
Hmm, it works at Femke, not at me...

**Comment by richelbilderbeek** [comment]
Of course, for v[i], i must be less *or equal* to `length(v)`, unlike C++

**Comment by richelbilderbeek** [comment]
Some runtimes I measure on my computer, times are in seconds:

```
df_time <- data.frame(
  n = c(2000, 10000, 15000, 20000, 40000),
  t = c(1.69, 9.553, 24.96, 42.41, 120.2)
)
ggplot2::qplot(data = df_time, x = df_time$n, y = df_time$t)
```

Assuming linear growth (and I do not) for the full dataset of 2M, I predict `50 * 2 min = 100 min`.

**Comment by richelbilderbeek** [comment]
After a meeting with @FemkeThon, we decided to run the code on my computer and create a `.csv` from it. It is running as we speak, ETA 12:00

**Comment by richelbilderbeek** [comment]
15:14: Still running...

**Comment by FemkeThon** [comment]
Solved.
