### ISSUE TITLE
Error vignettes (nLTT)

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#48]
Quitting from lines 236-238 (worked_out_examples.Rmd) 
Error: 'get_nltt_values' is not an exported object from 'namespace:nLTT'
Execution halted

nLTT:::get_nltt_values does not work, neither does 'clean and rebuild'

What to do?

**Comment by richelbilderbeek** [comment]
Excellent question!

In the [install_r_packages.R](https://github.com/richelbilderbeek/Cer2016/blob/master/install_r_packages.R) a new line is added:

```
devtools::install_github("richelbilderbeek/nLTT")
```

Run this in R to get the nLTT package installed.

**Comment by JolienGay** [comment]
Vignette works again, but I already had the nLTT package, did something change in it?

**Comment by richelbilderbeek** [comment]
Yes, me and its maintainer (Thijs Janzen) are merging our code.

**Comment by JolienGay** [comment]
Ok! Thx for the help!
