### ISSUE TITLE
Incipient species trees

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#51]
The incipient species tree in 'research_demo' shows incipient species in gray while the incipient tree in 'worked_out_examples' does not. I need the one in the latter for the ppt but could not find significant differences in the code. How do I get the grey lines to work?

**Comment by richelbilderbeek** [comment]
The difference in the vector called `colors`.

Here the incipient species are gray, good species black:

```
colors <- setNames(c("gray","black"), c("i","g"))
```

Here the incipient species are red, good species black:

```
colors <- setNames(c("red","black"), c("i","g"))
```

Example of using those colors:

```
phytools::plotSimmap(
  read_file(filename)$pbd_output$igtree.extant, 
  colors = colors
)
```

**Comment by richelbilderbeek** [comment]
@JolienGay : fixed it?

**Comment by JolienGay** [comment]
No, can't get the research demo to work anymore. Also when looking at the code, both color vectors are the same for me [colors <- setNames(c("gray","black"), c("i","g"))].

**Comment by richelbilderbeek** [comment]
For examples 1 and 3, everything should remain black as there is no protractedness there. Would that be an insight?

**Comment by JolienGay** [comment]
Yes.. I obviously did not concider that.. Still how do I get the whole set of steps for the ppt? I can't get the posterior to work in the research demo (there isn't one) and trying to copy paste the code from the other vignette fails to work.

**Comment by richelbilderbeek** [comment]
Why does obtaining the posterior fail? What is the error message given? Also do not forget that

```
file <- read_file("file.txt")
```

works on folder `Cer2016` when run manually, but in folder `Cer2016/vignettes` when `knitr` is active. That is why I often check with `file.exists` if it can be found.

Does that help?

**Comment by JolienGay** [comment]
When trying to knit the researsh_demo I get this message:

Quitting from lines 136-139 (research_demo.Rmd) 
Error in add_species_trees(filename, add_outgroup = TRUE) : 
  argument "verbose" is missing, with no default
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> add_species_trees
Execution halted

I don't understand the "verbose" thing.

I will certainly check later but will finish some of Femkes graphs first for the ppt. 
Thx for the help!

**Comment by richelbilderbeek** [comment]
Happy to help!

```
Error in add_species_trees(filename, add_outgroup = TRUE) :
argument "verbose" is missing, with no default
```

means that the function `add_species_trees` needs a value for `verbose`

Replace

```
add_species_trees(filename, add_outgroup = TRUE)
```

by 

```
add_species_trees(filename, add_outgroup = TRUE, verbose = FALSE)
```

should do the trick.

**Comment by JolienGay** [comment]
Oh ofc, it says it is an argument! The weird name threw me off =). I will try it but do not close this issue yet please.

**Comment by richelbilderbeek** [comment]
Ha, that sounds like a growth in insight :smiley: !

**Comment by JolienGay** [comment]
I think I did something wrong. I tried to update the analyze_gammas vignette with the nicer graphs but got a merge conflict as expected. I tried to fix it but lost all the ggplot codes that I added. While this is not a real problem (I will get them back faster than before) I am afraid I also resetted Femkes work.

**Comment by richelbilderbeek** [comment]
This happens once in a while. You can find Femke's code in the code in the `commits`.  Will you do it, so that @FemkeThon does not need to do this?

**Comment by JolienGay** [comment]
(The ambrose argument fixed the vignette problem btw, but I only see sampled trees from the posterior, not the posterior itself)

**Comment by JolienGay** [comment]
I never done that and don't know how, neither have I finished any work I planned to do =(

**Comment by richelbilderbeek** [comment]
Then I'll do that. Give me a sec...

**Comment by JolienGay** [comment]
Sorry! And thank you!

**Comment by richelbilderbeek** [comment]
No problems, that's what git is for. [Here](https://github.com/richelbilderbeek/Cer2016/commit/59b6c07d2157f4c63b6ab159710b34d03a99116c) I spot it, but I will talk to Femke first. I'd bet there is no problem at all: here new code will just merge...

**Comment by JolienGay** [comment]
That would be nice. I'll redo the ggplot2 codes now.

**Comment by richelbilderbeek** [comment]
Me and @FemkeThon merged everything manually. You did some great stuff there!

**Comment by richelbilderbeek** [comment]
Can this issue be closed (note: you can still view it, at the Closed Issues)?

If yes, you have the honour of doing this yourself :+1:

**Comment by JolienGay** [comment]
Ok! Everything seems to work again. I'm calling it a day =).
