### ISSUE TITLE
File corruption not random.

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#55]
All posterior files after ```article_1_5_5_2_2.RDA``` appear to be corrupted.

**Comment by richelbilderbeek** [comment]
As in file creation date?

**Comment by richelbilderbeek** [comment]
So, 

 * the parameter files are corrupted randomly
 * For `A` > 1, no posteriors are created, probably because they took longer than 10 days to run

**Comment by FemkeThon** [comment]
Pretty much.

**Comment by richelbilderbeek** [comment]
Well done! IMHO, we can close the Issue. Want to have the honor?

**Comment by FemkeThon** [comment]
Sure.
