### ISSUE TITLE
New version of rBEAST

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#56]
Tip for @FemkeThon  and @JolienGay :

Run this in RStudio

```
devtools::install_github("olli0601/rBEAST")
```

to get the newest version of rBEAST.

A lot of warnings will be removed, thanks to your truly.

**Comment by FemkeThon** [comment]
Ah, nice!

**Comment by richelbilderbeek** [comment]
It has been done.
