### ISSUE TITLE
Detailed feedback presentation?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#58]
@JolienGay : if and only if you like, I can give some detailed feedback on the presentation. You probably already have a lot you want to change, let me know when you need my precise eye.

**Comment by JolienGay** [comment]
It will take me a while to finish the ppt for today (after 5 pm) due to some stuff but I would appreciate feedback ofc. Maybe tomorrow when most is done? I planned on adding a few dias with the gamma stuff and ofc the parameterfile example. But other than that I don't know what you mean with "You probably already have a lot you want to change". The only other thing I thought I needed to do today was the poster.

**Comment by richelbilderbeek** [comment]
> Maybe tomorrow when most is done?
Whenever you need it.

**Comment by JolienGay** [comment]
Ok thx!

**Comment by FemkeThon** [comment]
Jolien, the results are going to look quite different, don't worry about that part too much.

**Comment by richelbilderbeek** [comment]
Just some notes I scribbled down, I put them here for safekeeping:

 * There are some references missing, e.g. where is read that the slowdown effect is caused by incomplete sampling?
 * There is a slide in which the slowdown in the LTT is shown (with a.o. the *dendroica*) and compared to the expected LTT. The left figure (the expected average LTT for a BD sim) has a linear y-scale, where the figure from Etienne&Rosindell uses a logarithmic y-scale.
 * The reason one individual per species is sampled is not because BEAST2 cannot support this, but it does assume a monophyletic species tree. Here is an example of a paraphyletic tree (at the top), and two sampled species trees

![paraphyly](https://cloud.githubusercontent.com/assets/2098230/15575651/3b79fc62-2354-11e6-8267-e82783073a3d.png)

**Comment by JolienGay** [comment]
Thanks, I will implement it.

**Comment by JolienGay** [comment]
I think I sometimes confuse some things during the ppt.. So BEAST2 assumes a monophyletic species tree because of the assumptions of the pure BD model. Because of the instant speciation rate not allowing for multiple individuals for a given species?

**Comment by richelbilderbeek** [comment]
Correct: if speciation is instantaneous, all trees will monophyletic. One *can* add multiple individuals per species in BEAST2, but then it will infer one monophyletic species tree (see #11), which may be misinformative.

**Comment by JolienGay** [comment]
Understood! About the age, this was the total length of the tree?

**Comment by richelbilderbeek** [comment]
Correct. `15` denotes fifteen million years

**Comment by JolienGay** [comment]
Ok! Last question about the parameter file and I think I get it then. I have highlighted 7 important parameters in an example file: the 5 PBD parameters, the age and mutation rate. The mutation rate is necessary to generate the alignments to get the data into BEAST. Is this correct?

**Comment by richelbilderbeek** [comment]
> the 5 PBD parameters, the age and mutation rate
There is also DNA sequence/alignment length

> The mutation rate is necessary to generate the alignments to get the data into BEAST. Is this correct?
Yes

**Comment by JolienGay** [comment]
Oh right! I'll highlight that one as well, thanks!

**Comment by JolienGay** [comment]
I ment tippy sorry >.< not stemmy

**Comment by JolienGay** [comment]
And changed my mind again to stemmy, since I think tippy represents the pure BD again where speciation is assumed to happen instantly.

**Comment by JolienGay** [comment]
Still confused, found nice trees in this article: 
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0115132#pone-0115132-g002 

S1_Figure and S2_Figure: I intend to use these as example in the ppt but they explain tippy and stemmy differently than @Femke did. I don't know if this is because I interpret it wrong or Femke confused the drawings, nevertheless I will use the article in the ppt and call it a day. _

**Comment by FemkeThon** [comment]
No, gamma < 0.

**Comment by FemkeThon** [comment]
Ehm... seems like that other article we saw used the terms the other way around...

**Comment by FemkeThon** [comment]
http://www.nature.com/ncomms/2015/151117/ncomms9837/full/ncomms9837.html#f3 =/

So which one is it?

**Comment by FemkeThon** [comment]
http://www.biologie.ens.fr/phyloeco/pdf/Manceauetal2015ELE.pdf

So, I think it is stemmy if there are many nodes close to the root after all

**Comment by JolienGay** [comment]
If it is like you say, I don't understand it and can't explain it properly tomorrow in the presentation. Richel will help us out of our misery ;P.

**Comment by JolienGay** [comment]
But, the printed article we got from Richel (Testing macro-evolutionary models using incomplete molecular phylogenies) seems to aggree with the first article. So does this one: http://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2012.00759.x/abstract

Again, could be interpreting it wrong, but it took a long time to figure out and I'm a little tired =P.

**Comment by FemkeThon** [comment]
It seems like the terms are used to mean both. That's annoying.

**Comment by richelbilderbeek** [comment]
AFAIKS, one needs a tree with four taxa to being able to explain the difference:

```
           +--
  +--------+
  |        +--
--+
  |        +--
  +--------+
           +--
```

```
    +---------
  +-+
  | +---------
--+
  | +---------
  +-+
    +---------
```

I'd bet all of us think the same which of these trees is stemmy and tippy?

**Comment by richelbilderbeek** [comment]
Davies & Buckley:

```
We find the phylogeny [...] is imbalanced and ‘stemmy’ (long branches towards the root), [...]. In contrast, the [...] is balanced and ‘tippy’ (long branches towards the tips), more consistent with the slow accumulation of diversity over long times [...].
```

**Comment by richelbilderbeek** [comment]
My feedback, feel free to ignore :-) . I've added checkboxes :sunglasses: 

 * [ ] The `Pull Of The Present` is something else than what you mention. I suggest not to mention it: The POTP is a simulation artefact, that does not exist in nature
 * [ ] Mention more: BD is a subset of PBD models in which SCR is infinite. The parameter sets with SCR = 1M are therefore special
 * [ ] Be more certain about the conclusion: you may conclusively have found that the gamma statistic is recovered correctly. OTOH, how much information is lost when summarizing a tree to a single value?
 * [ ] Be less certain about the conclusion: there are many more summary statistics. 
 * [ ] Mention gamma statistic references
 * [ ] Perhaps use the simpler trees I put in the `demo_gamma_statistic` vignette
 * [ ] Rainbow-colored graph comparing gamma statistic distributions could be zoomed in more

**Comment by JolienGay** [comment]
Perhaps use the simpler trees I put in the demo_gamma_statistic vignette:
I actually really like this example, and everything fits now. Would you be mad (=P) if I let it as it is?

**Comment by JolienGay** [comment]
On the other hand.. it does look clearer...I shall admit defeat.

**Comment by richelbilderbeek** [comment]
As I said: `feel free to ignore` and follow your own personal preferences.

**Comment by richelbilderbeek** [comment]
Presentation has been done. Well done!
