### ISSUE TITLE
Gammas of PBD and BD suspiciously similar

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#59]
See the last commit - there doesn't seem to be a difference between the PBD and the BD graph. I'll take another look at it (plot /only/ the PBD and see if that is different) but the 'complete' comparison and the BD seems remarkably alike.

**Comment by richelbilderbeek** [comment]
Perhaps because you plot the same :smile: ?

![issue](https://cloud.githubusercontent.com/assets/2098230/15572165/244e7eb0-233f-11e6-82ef-9cb0212cb32f.png)

**Comment by FemkeThon** [comment]
Oops. But my point still stands, with the update.

**Comment by richelbilderbeek** [comment]
Taking a look at it. Just as a note: I do see these useless values:

![1343](https://cloud.githubusercontent.com/assets/2098230/15573532/035e7b84-2348-11e6-8787-678206247858.png)

**Comment by FemkeThon** [comment]
Why are those useless? They mean that the gamma of the sampled tree and the posterior are exactly the same.

**Comment by FemkeThon** [comment]
Oh wait, nevermind. Yes, those are useless.

**Comment by richelbilderbeek** [comment]
A speciation completion rate of zero denotes that the initial two species may initiate speciation, but will never complete those. In the end [...].

Ah, you've found out :-)

**Comment by richelbilderbeek** [comment]
I suggest to wait until you've filtered these out. OK?

**Comment by FemkeThon** [comment]
Ok. Wait for what?

**Comment by richelbilderbeek** [comment]
Until you've removed the zeroes from the selection. OK?

**Comment by richelbilderbeek** [comment]
Which you did with commit f3a814af3d42a6a87634017547c2437178e17f5e . I will take a look...

**Comment by richelbilderbeek** [comment]
An idea: plot the diffs for different values *overlapping* for the different speciation completion rates. This may take some minutes...

**Comment by richelbilderbeek** [comment]
Got it working in isolation:

![pretty](https://cloud.githubusercontent.com/assets/2098230/15574526/2d68c0be-234e-11e6-8903-27865207b92b.png)

**Comment by FemkeThon** [comment]
Gonna try to do the overlap in a minute.

**Comment by richelbilderbeek** [comment]
Let's see who commits first :rocket:

**Comment by richelbilderbeek** [comment]
Very close ....

![pretty](https://cloud.githubusercontent.com/assets/2098230/15576150/c38c09ae-2356-11e6-931f-acd679ade434.png)

**Comment by richelbilderbeek** [comment]
Won with commit ab8a5f5d83a58c2a262eda63f3c2dcd282275c2a

Check the file `analyse_gammas_richel.Rmd`

I guess you can fix the scaling :crown:

**Comment by richelbilderbeek** [comment]
Just for the record: I won :sunglasses:
