### ISSUE TITLE
Error: unable to read askpass response from 'rpostback-askpass'

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#6]
error: unable to read askpass response from 'rpostback-askpass'
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by richelbilderbeek** [comment]
Description of fix is here:

https://github.com/OHI-Science/ohicore/issues/104

Sure, I'll help if you cannot figure that one out :-)

**Comment by JolienGay** [comment]
Hoi, ik ben beetje aan het prutsen op GitHub en zag dit staan. Is het de bedoeling dat ik iets doe met die fix? Wat ik eruit begrijp is dat het op de computer op de uni (met linux) gebeurt is. Atm zit ik op mn laptop met windows.

**Comment by richelbilderbeek** [comment]
You can close this issue, if you've solved it, preferably with a link to where you found the solution. That way, you can always look it up later again.

**Comment by richelbilderbeek** [comment]
I found that the solution did not work. A `git push` from the command-line is still rock-solid though :-)

**Comment by richelbilderbeek** [comment]
A newer version of RStudio may fix the problem. Looks like the command line is the way to go now.
