### ISSUE TITLE
Detailed feedback poster?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#60]
@JolienGay : ofc I am happy to supply detailed feedback on the poster as well :+1:

**Comment by FemkeThon** [comment]
It would be much appreciated. It's not finished yet, but there's a detailed outline now.

**Comment by richelbilderbeek** [comment]
![1](https://cloud.githubusercontent.com/assets/2098230/15626225/c21b4944-24bf-11e6-9bab-3a54a3439355.png)

**Comment by richelbilderbeek** [comment]
The underside of `g` and `p` fall off, may be just to `.pptx`

![2](https://cloud.githubusercontent.com/assets/2098230/15626226/c9c6e32e-24bf-11e6-8c92-a9ee51cb28ff.png)

**Comment by richelbilderbeek** [comment]
Personally, I prefer my own pretty picture:

![my_pretty_picture](https://cloud.githubusercontent.com/assets/2098230/15626245/6d11565e-24c0-11e6-8fb6-0b5198e69e67.png)

Feel free to yes/no use it.

**Comment by richelbilderbeek** [comment]
Make the link between BD, PBD and SCR more explicit in the trees.

![4](https://cloud.githubusercontent.com/assets/2098230/15626282/a69b95b4-24c1-11e6-9778-f216446867af.png)

(personally, I like pointy clouds, like those used in ads. Please prefer your own taste over mine)

**Comment by richelbilderbeek** [comment]
I miss the explanation of the gamma stat. Perhaps this vignette can help :sunglasses: ?

![demo_gamma_stat](https://cloud.githubusercontent.com/assets/2098230/15626349/5a9a6436-24c3-11e6-8de0-5de9ee56acd7.png)

**Comment by richelbilderbeek** [comment]
> In nature, speciation takes time. 
> Despite this, many phylogenetic inference programs like BEAST2 use models that assume speciation to happen instantly. One of those models is the pure Birth-Death model (BD), which predicts an increase in lineages over time at a constant rate.  However,  experimental data show a slowdown in lineage accumulation towards the present, contrary to the assumptions of BD. 
> An extension of this model, the Protracted BD model (PBD), allows for speciation to take time, adding an incipient stage before a species becomes a good species. The effect this protractedness has on reconstructing phylogenies is currently unknown.  
> In this research, we test if BEAST2, a popular phylogenetic inference program based on BD, can accurately recover trees that were simulated using the assumptions of PBD.

I enjoy the 'Fact, problem, possible solution, this research' build-up. 

I personally do find it too long and detailed. I would phrase it more general, something in range of this:

> We know speciation takes time.
> We ignore this fact in phylogeny inference, due to computation constraints
> So if in nature speciation takes time, how wrong have our inferences been?
> The new PBD model adds speciation taking time and allows us to answer this question in silico.
> This research measures the error a popular phylogeny inferring tool makes

I think we agree on this being simpler and shorter. But pick any intermediate.

**Comment by richelbilderbeek** [comment]
Another well-phrased piece of text I personally find too long:

> Other parameters seem to have more impact on the correct recovery of a PBD tree than the SCR, and with that protractedness. For this reason, with the results we have now, we think it is not necessary to include PBD in BEAST2. However, the gamma statistic is a summery of the tree in one number – there might well be other problems that gamma doesn’t detect. This is why it would be prudent to look at other methods of comparing the sampled species trees and the posterior before being too certain about this conclusion. 

A bit clumsily phrased still (but well, it is a work in progress), eloquent, yet IMHO too long winded.

My two cents:

> The gamma statistic was recovered well under all parameter settings. It was expected to deviate most when speciation takes more time, but other parameters were more influential. BEAST2 thus does well at recovering the gamma statistic even when speciation in nature takes time. How well other statistics are recovered is unknown.

Again, feel free to mix the two or ignore mine

**Comment by richelbilderbeek** [comment]
I suggest to remove the `0.4`. It has been an experimental error, and it may be an outlier as it probably also had deviating other parameters as well.

![5](https://cloud.githubusercontent.com/assets/2098230/15626546/7267799c-24c7-11e6-9343-45a4c6a181bf.png)

**Comment by richelbilderbeek** [comment]
@FemkeThon I see good progres in the poster! Next to the compliments, I've put the desired/required nitpicking above. Feel free to ignore all. Let me know if you'd want me to take another look.

**Comment by FemkeThon** [comment]
0.4 was an error, that's right - and this means that 0.2 and 0.8 were as well? I'm asking because the lines for those look very similar to 0.4.

**Comment by FemkeThon** [comment]
@richelbilderbeek  I think we have changed enough that another round of feedback could be useful.

**Comment by richelbilderbeek** [comment]
IMHO this is an awesome poster!

**Comment by richelbilderbeek** [comment]
Poster has been printed.
