### ISSUE TITLE
Finishing poster

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/Cer2016#63]
@richelbilderbeek I get this error when trying to knit the demo_gamma_stat
> pandoc.exe: pdflatex not found. pdflatex is needed for pdf output.
Error: pandoc document conversion failed with error 41

I only have the previous pdf in my local file, where the third tree has not been added yet. Could you remake the pdf? 

Almost finished with the poster btw!

**Comment by JolienGay** [comment]
Never mind!

**Comment by richelbilderbeek** [comment]
For your reference: this error is caused because the document type was set to `pdf_document`. This must be set to `html_vignette` or (what I do on Windows) `word_document`
