### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by FemkeThon** [richelbilderbeek/Cer2016#64]
@richelbilderbeek 

Could you print the file in doc/print_this_please.pdf please? We finished it.

**Comment by richelbilderbeek** [comment]
Awesome, I will have it printed before 9:00.

**Comment by FemkeThon** [comment]
Ok, apparently the poster was changed, @richelbilderbeek , please print print_this_please2 instead!

**Comment by JolienGay** [comment]
If it is already done it doesn't have to ofc, I din't see the comment about printing before 9h when I did it.

**Comment by FemkeThon** [comment]
9 AM tomorrow though.

**Comment by richelbilderbeek** [comment]
Done, they're on the table
