### ISSUE TITLE
Travis quits due to 30 min inresponsiveness

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Cer2016#75]
[Here is a fix](http://www.r-bloggers.com/travis-ci-you-have-too-many-tests-lolz). Thanks to @randyzwitch for this IMHO awesome article!

**Comment by randyzwitch** [comment]
👍

**Comment by richelbilderbeek** [comment]
Works just fine since a2f335f13afad8539c395b493e07d56355c5b13a
